# Quantum Information 101

### **Victor Onofre**

In [1]:
import matplotlib.pyplot as plt
import qutip as qt
import numpy as np

### Density operator

$$\rho = \sum_{i} p_{i} |\psi_{i} > < \psi_{i}|$$

 \begin{equation}
|0> =
\begin{bmatrix} 
1     \cr
0     \end{bmatrix}  \qquad
|1> =
\begin{bmatrix} 
0     \cr
1     \end{bmatrix}  
\end{equation}


In [2]:
zero = qt.basis(2,0)
one  = qt.basis(2,1)

Example:

$$|\psi > = \sqrt{0.2} |0> + \sqrt{0.8} |1>$$

In [3]:
psi = np.sqrt(0.2)*zero + np.sqrt(0.8)*one

$< \psi_{i}|\psi_{i} >$

In [4]:
psi.dag()*psi

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[1.]]

$$\rho = \sum_{i} p_{i} |\psi_{i} > < \psi_{i}| = |\psi > < \psi| =  (\sqrt{0.2} |0> + \sqrt{0.8} |1>) (\sqrt{0.2} <0| + \sqrt{0.8} <1|)$$
$$ = 0.2 |0> <0| + \sqrt{0.2}\sqrt{0.8}|0><1| + \sqrt{0.2}\sqrt{0.8}|1><0| + 0.8 |1> <1| $$

In [5]:
rho = psi*psi.dag()
rho

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.2 0.4]
 [0.4 0.8]]

The evolution of the density operator is described by the equation

$$\rho = \sum_{i} p_{i} |\psi_{i} > < \psi_{i}| \rightarrow \sum_{i} p_{i} U |\psi_{i} > < \psi_{i}| U^{\dagger} = U \rho U^{\dagger} $$

A measurement described by the operators $M_{m}$, with the initial state in $|\psi_{i}>$. Then the probability of gettting $m$ is 

$$p(m|i) = <\psi_{i}|M_{m}^{\dagger}M_{m} |\psi_{i}> = tr(M_{m}^{\dagger}M_{m}|\psi_{i} > < \psi_{i}|  ) $$

where we have used the equation:
$$tr(A |\psi> <\psi|) = \sum_{i} <i| A |\psi> <\psi|i> = <\psi|A| \psi> $$

$$M_{1}= |0><0|$$

$$ tr(|0><0| |0><0|  |\psi > < \psi| ) = tr(|0><0|  |\psi > < \psi| )  = tr\Big[ |0><0|  \Big(0.2 |0> <0| + \sqrt{0.2}\sqrt{0.8}|0><1| + \sqrt{0.2}\sqrt{0.8}|1><0| + 0.8 |1> <1| \Big)  \Big]  $$

$$ = tr\Big[ 0.2 |0> <0| + \sqrt{0.2}\sqrt{0.8}|0><1|  \Big]   = 0.2$$

In [6]:
M1 = zero*zero.dag()
M1

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [7]:
p0 =( (M1.dag()*M1)*rho ).tr()
p0

0.19999999999999998

In [8]:
p0 =( M1*rho ).tr()
p0

0.19999999999999998

An operator $\rho$ is the desity operator associtate to some ensemble $\{ p_{i}, |\psi_{i}>\}$ if and only if it satisfies the conditions:

(1) **Trace condition** $\rho$ has trace equal to one $tr(\rho) = 1$

$$ tr(\rho) = \sum_{i} p_{i} tr(|\psi_{i} > < \psi_{i} |) = \sum_{i} p_{i} = 1 $$

(2) **Positivity condition** $\rho$ is a positive operator $<\phi | \rho | \phi> \geq 0$

Suppose $|\phi>$ is an arbitrary vector in state space. Then 

$$<\phi | \rho | \phi> = \sum_{i} p_{i} <\phi|\psi_{i} > <\psi_{i} | \phi >  = \sum_{i} p_{i} |< \phi|\psi_{i} > |^{2} \geq 0$$

In [9]:
rho.tr()

0.9999999999999999

## Reduced density operator

The reduced density operator is so useful as to be virtually indispensable in the analysis of composite quantum systems. Suppose we have a physicial systems $A$ and $B$, whose state is desbribed by a density operator $\rho^{AB}$. The reduced densitu operator for system $A$ is defined by 

$$ \rho^{A} = tr_{B}(\rho^{AB})$$

where $tr_{B}$ is the **partial trace** over system $B$.

$$ tr_{B}(\rho^{AB}) = tr_{B} \Big( |a_{1}> <a_{2}| \otimes |b_{1}> <b_{2}| \Big) = |a_{1}> <a_{2}|  tr( |b_{1}> <b_{2}|)  $$

$$\rho_{1} = tr_{2}(\rho_{12}) = \sum_{\alpha} <\alpha_{2}|\rho |\alpha_{2}> $$

$$\rho_{2} = tr_{1}(\rho_{12}) = \sum_{i} <i_{1}|\rho |i_{1}> $$

Example in the bell state:

$$|\Phi > = \frac{|00> + |11> }{\sqrt{2}} $$

$$\rho = |\Phi > < \Phi| = \Big( \frac{|00> + |11> }{\sqrt{2}} \Big)  \Big( \frac{<00| + <11| }{\sqrt{2}} \Big) =  \frac{|00> <00| + |11> <00|+ |00> <11|+ |11> <11|}{2}  $$

In [10]:
zero_zero = qt.tensor(zero,zero)
zero_zero

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [11]:
one_one = qt.tensor(one,one)
one_one

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]

In [12]:
bell_state = (zero_zero +  one_one)*(1/np.sqrt(2))
bell_state 

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]

In [13]:
rho_bell = bell_state*(bell_state.dag())
rho_bell

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

$$\rho^{1} = tr_{2}(\rho) =   \frac{tr_{2}(|00> <00|) + tr_{2}(|11> <00|) + tr_{2}(|00> <11|)+ tr_{2}(|11> <11|) }{2}  $$


$$\rho^{1} = tr_{2}(\rho) =   \frac{|0> <0| <0|0> +|1> <0| <0|1> + |0> <1| <1|0> + |1> <1| <1|1>  }{2}  $$

$$\rho^{1} = tr_{2}(\rho) =   \frac{|0> <0| + |1> <1|  }{2} = \frac{I}{2}  $$

In [16]:
rho_bell.ptrace(1)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]

# The Kraus representation

$$\rho_{AB} = \rho_{A} \otimes |0_{B}> <0_{B}| $$

Subsystem $B$ is in a pure state. The evolution of the total system is governed by the unitary operator $U^{AB}$ which leads to the new density matrix

$$\rho_{AB}' = U^{AB} \rho_{12} (U^{AB})^{\dagger} = U^{AB} \Big( \rho_{A} \otimes |0_{B}> <0_{B}  \Big) U^{AB})^{\dagger}  $$

We are interested in the new matrix $\rho_{AB}'$ descrbing subsystem 1, we must trace over the second subsystem:

$$\rho_{A}' =  Tr_{B}(\rho_{AB}') = Tr_{B} \Big[U^{AB} \Big( \rho_{A} \otimes |0_{B}> <0_{B}| \Big) U^{\dagger} \Big]  = Tr_{B} \Big[ U^{AB} \Big( \rho_{A}|0_{B}> <0_{B}| \Big) U^{\dagger} \Big]   = Tr_{B} \Big[ U^{AB} \Big( |0_{B}>\rho_{A} <0_{B}| \Big) (U^{AB})^{\dagger}  \Big]  =\sum_{k} < k _{B}|U^{AB}  |0_{B}> \rho_{A} <0_{B}| (U^{AB})^{\dagger}  |k_{B}> $$

where $\{ |k_{B}> \} $ is a basis set for thje Hilbert space $H_{B}$ associated with subsystem $B$. $< k _{B}|U^{AB}  |0_{B}> $ is an operator acting on the Hilbert space $H_{A}$ associated with sussytem $A$

Example:
 
$$\rho^{AB} = \rho^{A} \otimes |0_{B} > <0_{B}| $$

$$U^{AB} = \frac{1}{\sqrt{2}} \Big(\sigma_{x}^{A} \otimes I^{B}  + \sigma_{y}^{A} \otimes \sigma_{x}^{B}  \Big) $$

$$\rho_{AB}' =U^{AB} \rho_{AB} (U^{AB})^{\dagger} = $$

$$ =\frac{1}{2} \Big\{ \sigma_{x}^{A} \rho_{A}  \sigma_{x}^{A} \otimes | 0_{B} > <0_{B} | +  \sigma_{y}^{A} \rho_{A}  \sigma_{y}^{A} \otimes | 1_{B} > <1_{B} |  +  \sigma_{x}^{A} \rho_{A}  \sigma_{x}^{A} \otimes | 0_{B} > <1_{B} |  +  \sigma_{y}^{A} \rho_{A}  \sigma_{x}^{A} \otimes | 1_{B} > <0_{B} |  \Big\}  $$

$$ \rho_{A} \rightarrow \rho_{A}' = Tr_{B}[\rho_{AB}'] = \frac{1}{2} \Big\{ \sigma_{x}^{A} \rho^{A} \sigma_{x}^{A} +  \sigma_{y}^{A} \rho^{A} \sigma_{y}^{A}   \Big\} $$

$$\rho_{A}' = \varepsilon(\rho_{A}) = \sum_{i=1}^{2} K_{i}^{A} \rho_{A} (K_{i}^{A})^{\dagger} $$

$$K_{1}^{A} = \frac{1}{\sqrt{2}} \sigma_{x}^{A} \quad K_{2}^{A} = \frac{1}{\sqrt{2}} \sigma_{y}^{A} $$