# Quantum Information 101

### **Victor Onofre**

In [2]:
import matplotlib.pyplot as plt
import qutip as qt
import numpy as np

### Density operator

$$\rho = \sum_{i} p_{i} |\psi_{i} > < \psi_{i}|$$

 \begin{equation}
|0> =
\begin{bmatrix} 
1     \cr
0     \end{bmatrix}  \qquad
|1> =
\begin{bmatrix} 
0     \cr
1     \end{bmatrix}  
\end{equation}


In [3]:
zero = qt.basis(2,0)
one  = qt.basis(2,1)

In [5]:
one

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

Example:

$$|\psi > = \sqrt{0.2} |0> + \sqrt{0.8} |1>$$

In [7]:
psi = np.sqrt(0.2)*zero + np.sqrt(0.8)*one
psi

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.4472136 ]
 [0.89442719]]

$< \psi_{i}|\psi_{i} >$

In [8]:
psi.dag()*psi

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[1.]]

$$\rho = \sum_{i} p_{i} |\psi_{i} > < \psi_{i}| = |\psi > < \psi| =  (\sqrt{0.2} |0> + \sqrt{0.8} |1>) (\sqrt{0.2} <0| + \sqrt{0.8} <1|)$$
$$ = 0.2 |0> <0| + \sqrt{0.2}\sqrt{0.8}|0><1| + \sqrt{0.2}\sqrt{0.8}|1><0| + 0.8 |1> <1| $$

In [9]:
rho = psi*psi.dag()
rho

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.2 0.4]
 [0.4 0.8]]

The evolution of the density operator is described by the equation

$$\rho = \sum_{i} p_{i} |\psi_{i} > < \psi_{i}| \rightarrow \sum_{i} p_{i} U |\psi_{i} > < \psi_{i}| U^{\dagger} = U \rho U^{\dagger} $$

A measurement described by the operators $M_{m}$, with the initial state in $|\psi_{i}>$. Then the probability of gettting $m$ is 

$$p(m|i) = <\psi_{i}|M_{m}^{\dagger}M_{m} |\psi_{i}> = tr(M_{m}^{\dagger}M_{m}|\psi_{i} > < \psi_{i}|  ) $$

where we have used the equation:
$$tr(A |\psi> <\psi|) = \sum_{i} <i| A |\psi> <\psi|i> = <\psi|A| \psi> $$

**Example:**

$$M_{1}= |0><0|$$

$$ tr(|0><0| |0><0|  |\psi > < \psi| ) = tr(|0><0|  |\psi > < \psi| )  = tr\Big[ |0><0|  \Big(0.2 |0> <0| + \sqrt{0.2}\sqrt{0.8}|0><1| + \sqrt{0.2}\sqrt{0.8}|1><0| + 0.8 |1> <1| \Big)  \Big]  $$

$$ = tr\Big[ 0.2 |0> <0| + \sqrt{0.2}\sqrt{0.8}|0><1|  \Big]   = 0.2$$

In [10]:
M1 = zero*zero.dag()
M1

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [11]:
p0 =( (M1.dag()*M1)*rho ).tr()
p0

0.19999999999999998

In [12]:
p0 =( M1*rho ).tr()
p0

0.19999999999999998

An operator $\rho$ is the desity operator associtate to some ensemble $\{ p_{i}, |\psi_{i}>\}$ if and only if it satisfies the conditions:

(1) **Trace condition** $\rho$ has trace equal to one $tr(\rho) = 1$

$$ tr(\rho) = \sum_{i} p_{i} tr(|\psi_{i} > < \psi_{i} |) = \sum_{i} p_{i} = 1 $$

(2) **Positivity condition** $\rho$ is a positive operator $<\phi | \rho | \phi> \geq 0$

Suppose $|\phi>$ is an arbitrary vector in state space. Then 

$$\rho = \sum_{i} p_{i} |\psi_{i} > < \psi_{i}|$$

$$<\phi | \rho | \phi> = \sum_{i} p_{i} <\phi|\psi_{i} > <\psi_{i} | \phi >  = \sum_{i} p_{i} |< \phi|\psi_{i} > |^{2} \geq 0$$

In [13]:
rho.tr()

0.9999999999999999

## Reduced density operator

The reduced density operator is so useful as to be virtually indispensable in the analysis of composite quantum systems. Suppose we have a physicial systems $A$ and $B$, whose state is desbribed by a density operator $\rho^{AB}$. The reduced density operator for system $A$ is defined by 

$$ \rho^{A} = tr_{B}(\rho^{AB})$$

where $tr_{B}$ is the **partial trace** over system $B$.

$$ tr_{B}(\rho^{AB}) = tr_{B} \Big( |a_{1}> <a_{2}| \otimes |b_{1}> <b_{2}| \Big) = |a_{1}> <a_{2}|  tr( |b_{1}> <b_{2}|)  $$

$$\rho_{1} = tr_{2}(\rho_{12}) = \sum_{\alpha} <\alpha_{2}|\rho |\alpha_{2}> $$

$$\rho_{2} = tr_{1}(\rho_{12}) = \sum_{i} <i_{1}|\rho |i_{1}> $$

**Example in the bell state:**

$$|\Phi > = \frac{|00> + |11> }{\sqrt{2}} $$

$$|00> = |0> \otimes |0> $$

$$\rho = |\Phi > < \Phi| = \Big( \frac{|00> + |11> }{\sqrt{2}} \Big)  \Big( \frac{<00| + <11| }{\sqrt{2}} \Big) =  \frac{|00> <00| + |11> <00|+ |00> <11|+ |11> <11|}{2}  $$

In [14]:
zero_zero = qt.tensor(zero,zero)
zero_zero

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [15]:
one_one = qt.tensor(one,one)
one_one

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]

In [16]:
bell_state = (zero_zero +  one_one)*(1/np.sqrt(2))
bell_state 

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]

In [17]:
rho_bell = bell_state*(bell_state.dag())
rho_bell

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

$$\rho^{1} = tr_{2}(\rho) =   \frac{tr_{2}(|00> <00|) + tr_{2}(|11> <00|) + tr_{2}(|00> <11|)+ tr_{2}(|11> <11|) }{2}  $$


$$\rho^{1} = tr_{2}(\rho) =   \frac{|0> <0| <0|0> +|1> <0| <0|1> + |0> <1| <1|0> + |1> <1| <1|1>  }{2}  $$

$$\rho^{1} = tr_{2}(\rho) =   \frac{|0> <0| + |1> <1|  }{2} = \frac{I}{2}  $$

In [18]:
rho_bell.ptrace(1)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]

# The Kraus representation

$$\rho_{AB} = \rho_{A} \otimes |0_{B}> <0_{B}| $$

Subsystem $B$ is in a pure state. The evolution of the total system is governed by the unitary operator $U^{AB}$ which leads to the new density matrix

$$\rho_{AB}' = U^{AB} \rho_{12} (U^{AB})^{\dagger} = U^{AB} \Big( \rho_{A} \otimes |0_{B}> <0_{B}  \Big) U^{AB})^{\dagger}  $$

We are interested in the new matrix $\rho_{AB}'$ descrbing subsystem 1, we must trace over the second subsystem:

$$\rho_{A}' =  Tr_{B}(\rho_{AB}') = Tr_{B} \Big[U^{AB} \Big( \rho_{A} \otimes |0_{B}> <0_{B}| \Big) U^{\dagger} \Big]  = Tr_{B} \Big[ U^{AB} \Big( \rho_{A}|0_{B}> <0_{B}| \Big) U^{\dagger} \Big]   = Tr_{B} \Big[ U^{AB} \Big( |0_{B}>\rho_{A} <0_{B}| \Big) (U^{AB})^{\dagger}  \Big]  =\sum_{k} < k _{B}|U^{AB}  |0_{B}> \rho_{A} <0_{B}| (U^{AB})^{\dagger}  |k_{B}> $$

where $\{ |k_{B}> \} $ is a basis set for thje Hilbert space $H_{B}$ associated with subsystem $B$. $< k _{B}|U^{AB}  |0_{B}> $ is an operator acting on the Hilbert space $H_{A}$ associated with subsytem $A$

**Example:**



$$\rho^{AB} = \rho^{A} \otimes |0_{B} > <0_{B}| $$

$$\rho^{A} =  |\psi > < \psi|  = 0.2 |0> <0| + \sqrt{0.2}\sqrt{0.8}|0><1| + \sqrt{0.2}\sqrt{0.8}|1><0| + 0.8 |1> <1| $$

In [19]:
rho_B = zero*(zero.dag())
rho_B

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [20]:
rho

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.2 0.4]
 [0.4 0.8]]

In [21]:
rho_AB = qt.tensor(rho,rho_B)
rho_AB

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.2 0.  0.4 0. ]
 [0.  0.  0.  0. ]
 [0.4 0.  0.8 0. ]
 [0.  0.  0.  0. ]]

$$U^{AB} = \frac{1}{\sqrt{2}} \Big(\sigma_{x}^{A} \otimes I^{B}  + \sigma_{y}^{A} \otimes \sigma_{x}^{B}  \Big) $$

In [22]:
X_A = qt.sigmax()
X_A

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [28]:
X_B = qt.sigmax()

In [23]:
Y_A= qt.sigmay()
Y_A

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [26]:
I_B = qt.qeye(2)
I_B

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [29]:
U_AB = ( qt.tensor(X_A ,I_B ) + qt.tensor(Y_A, X_B)  ) / np.sqrt(2)
U_AB

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.        +0.j         0.        +0.j         0.70710678+0.j
  0.        -0.70710678j]
 [0.        +0.j         0.        +0.j         0.        -0.70710678j
  0.70710678+0.j        ]
 [0.70710678+0.j         0.        +0.70710678j 0.        +0.j
  0.        +0.j        ]
 [0.        +0.70710678j 0.70710678+0.j         0.        +0.j
  0.        +0.j        ]]

$$\rho_{AB}' =U^{AB} \rho_{AB} (U^{AB})^{\dagger} = $$

$$ =\frac{1}{2} \Big\{ \sigma_{x}^{A} \rho_{A}  \sigma_{x}^{A} \otimes | 0_{B} > <0_{B} | +  \sigma_{y}^{A} \rho_{A}  \sigma_{y}^{A} \otimes | 1_{B} > <1_{B} |  +  \sigma_{x}^{A} \rho_{A}  \sigma_{x}^{A} \otimes | 0_{B} > <1_{B} |  +  \sigma_{y}^{A} \rho_{A}  \sigma_{x}^{A} \otimes | 1_{B} > <0_{B} |  \Big\}  $$

In [30]:
rho_AB_prime = U_AB*rho_AB*(U_AB.dag())
rho_AB_prime

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.4+0.j   0. +0.4j  0.2+0.j   0. -0.2j]
 [ 0. -0.4j  0.4+0.j   0. -0.2j -0.2+0.j ]
 [ 0.2+0.j   0. +0.2j  0.1+0.j   0. -0.1j]
 [ 0. +0.2j -0.2+0.j   0. +0.1j  0.1+0.j ]]

$$ \rho_{A} \rightarrow \rho_{A}' = Tr_{B}[\rho_{AB}'] = \frac{1}{2} \Big\{ \sigma_{x}^{A} \rho^{A} \sigma_{x}^{A} +  \sigma_{y}^{A} \rho^{A} \sigma_{y}^{A}   \Big\} $$

In [31]:
rho_A = rho_AB_prime.ptrace(0)
rho_A

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.8 0. ]
 [0.  0.2]]

In [33]:
rho_A_test = (X_A*rho*X_A +  Y_A*rho*Y_A  )/2
rho_A_test

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.8 0. ]
 [0.  0.2]]

$$\rho_{A}' = \varepsilon(\rho_{A}) = \sum_{i=1}^{2} K_{i}^{A} \rho_{A} (K_{i}^{A})^{\dagger} $$

$$K_{1}^{A} = \frac{1}{\sqrt{2}} \sigma_{x}^{A} \quad K_{2}^{A} = \frac{1}{\sqrt{2}} \sigma_{y}^{A} $$

In [32]:
K1 = X_A/np.sqrt(2)
K1

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.         0.70710678]
 [0.70710678 0.        ]]

In [33]:
K2 = Y_A/np.sqrt(2)
K2

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j         0.-0.70710678j]
 [0.+0.70710678j 0.+0.j        ]]

In [34]:
rho_A_kraus = K1*rho*(K1.dag()) + K2*rho*(K2.dag())
rho_A_kraus

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.8 0. ]
 [0.  0.2]]

# **References:**

[1] Nielsen, M., & Chuang, I. (2010). Quantum Computation and Quantum Information: 10th Anniversary Edition. Cambridge: Cambridge University Press. doi:10.1017/CBO9780511976667

[2] Audretsch, J. (2006). T Entangled Systems: New Directions in Quantum Physics. Wiley-VCH
    